version: '3'

services:
  app:
    build:
      args:
        user: web
        uid: 1000
      dockerfile: ./Dockerfile

  db:
    image: postgres:12
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/conf.d/

volumes:
  db_data: